# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8
   
    steps:
      - checkout

      - run: mvn dependency:go-offline
     
      - run: mvn cobertura:cobertura
       
      # run tests!
      - run: mvn integration-test
     
- run: bash <(curl -s https://codecov.io/bash)
